### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, rust_cstr_free): symbol not found)

### ISSUE THREAD

**Issue by mikeooye** [TinoGuo/r_crypto#23]
Code below work fine on iOS simulator and Android devices, but throw exception on iOS devices.

```dart
var ret = rHash.filePath(HashType.SHA3_224, path);
```

The stack is 
```bash
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, rust_cstr_free): symbol not found)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31)
#1      _Loader.freeCString (package:r_crypto/src/basic/loader.dart)
package:r_crypto/…/basic/loader.dart:1
#2      _GrowableList.forEach (dart:core-patch/growable_array.dart)
#3      _Loader.freeCStrings (package:r_crypto/src/basic/loader.dart:72)
#4      _Hash.filePath (package:r_crypto/src/hash.dart:142)
#5      ObjectNameGenerator.getKey (package:aliyun_oss/src/name_generator.dart:10)
#6      ObjectNameGenerator.getName (package:aliyun_oss/src/name_generator.dart:33)
#7      AliyunOss.getObjectName (package:aliyun_oss/src/aliyun_oss.dart:345)
#8      _MessageSessionDetailPageState._uploadFile (package:flutter_yuanling_app/message_module/view/message_session_detail_page.dart:1391)
#9      _MessageSessionDetailPageState._buildChatInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_yuanling_app/message_module/view/message_session_detail_page.dart:712)
<asynchronous suspension>

```

**Comment by TinoGuo** [comment]
@mikeooye can u follow example? I used the iPhone device, all looks good

https://user-images.githubusercontent.com/4519784/133925331-b707b6d5-1678-4589-9e03-1d913e95ba74.MP4

**Comment by mikeooye** [comment]
Sorry，I just saw your email. I missed a condition, you should run the example in release mode.

**Comment by TinoGuo** [comment]
https://github.com/flutter/flutter/issues/18976 I added dummy method to avoid swift optimisation, I verified in profile, it should work from 0.5.0
